package com.akshay.project.DoctorOnCall.enums;

public enum SPECIALIZATION {
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    GYNECOLOGY,
    ONCOLOGY,
    PSYCHIATRY,
    RADIOLOGY,
    OPHTHALMOLOGY,
    UROLOGY,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    ANESTHESIOLOGY,
    SURGERY,
    IMMUNOLOGY,
    HEMATOLOGY

}
